var Skyblue = function() {
  
  var _colors = [
    { name: "AliceBlue",               values: [240, 248, 255],   category: "white"  },
    { name: "AntiqueWhite",            values: [250, 235, 215],   category: "white"  },
    { name: "Aqua",                    values: [  0, 255, 255],   category: "cyan"   },
    { name: "Aquamarine",              values: [127, 255, 212],   category: "cyan"   },
    { name: "Azure",                   values: [240, 255, 255],   category: "white"  },
    { name: "Beige",                   values: [245, 245, 220],   category: "white"  },
    { name: "Bisque",                  values: [255, 228, 196],   category: "brown"  },
    { name: "Black",                   values: [  0,   0,   0],   category: "gray"   },
    { name: "BlanchedAlmond",          values: [255, 235, 205],   category: "brown"  },
    { name: "Blue",                    values: [  0,   0, 255],   category: "blue"   },
    { name: "BlueViolet",              values: [138,  43, 226],   category: "purple" },
    { name: "Brown",                   values: [165,  42,  42],   category: "brown"  },
    { name: "BurlyWood",               values: [222, 184, 135],   category: "brown"  },
    { name: "CadetBlue",               values: [ 95, 158, 160],   category: "cyan"   },
    { name: "Chartreuse",              values: [127, 255,   0],   category: "green"  },
    { name: "Chocolate",               values: [210, 105,  30],   category: "brown"  },
    { name: "Coral",                   values: [255, 127,  80],   category: "orange" },
    { name: "CornflowerBlue",          values: [100, 149, 237],   category: "blue"   },
    { name: "Cornsilk",                values: [255, 248, 220],   category: "brown"  },
    { name: "Crimson",                 values: [220,  20,  60],   category: "red"    },
    { name: "Cyan",                    values: [  0, 255, 255],   category: "cyan"   },
    { name: "DarkBlue",                values: [  0,   0, 139],   category: "blue"   },
    { name: "DarkCyan",                values: [  0, 139, 139],   category: "cyan"   },
    { name: "DarkGoldenRod",           values: [184, 134,  11],   category: "brown"  },
    { name: "DarkGray",                values: [169, 169, 169],   category: "gray"   },
    { name: "DarkGreen",               values: [  0, 100,   0],   category: "green"  },
    { name: "DarkKhaki",               values: [189, 183, 107],   category: "yellow" },
    { name: "DarkMagenta",             values: [139,   0, 139],   category: "purple" },
    { name: "DarkOliveGreen",          values: [ 85, 107,  47],   category: "green"  },
    { name: "DarkOrange",              values: [255, 140,   0],   category: "orange" },
    { name: "DarkOrchid",              values: [153,  50, 204],   category: "purple" },
    { name: "DarkRed",                 values: [139,   0,   0],   category: "red"    },
    { name: "DarkSalmon",              values: [233, 150, 122],   category: "red"    },
    { name: "DarkSeaGreen",            values: [143, 188, 143],   category: "green"  },
    { name: "DarkSlateBlue",           values: [ 72,  61, 139],   category: "purple" },
    { name: "DarkSlateGray",           values: [ 47,  79,  79],   category: "gray"   },
    { name: "DarkTurquoise",           values: [  0, 206, 209],   category: "cyan"   },
    { name: "DarkViolet",              values: [148,   0, 211],   category: "purple" },
    { name: "DeepPink",                values: [255,  20, 147],   category: "pink"   },
    { name: "DeepSkyBlue",             values: [  0, 191, 255],   category: "blue"   },
    { name: "DimGray",                 values: [105, 105, 105],   category: "gray"   },
    { name: "DodgerBlue",              values: [ 30, 144, 255],   category: "blue"   },
    { name: "FireBrick",               values: [178,  34,  34],   category: "red"    },
    { name: "FloralWhite",             values: [255, 250, 240],   category: "white"  },
    { name: "ForestGreen",             values: [ 34, 139,  34],   category: "green"  },
    { name: "Fuchsia",                 values: [255,   0, 255],   category: "purple" },
    { name: "Gainsboro",               values: [220, 220, 220],   category: "gray"   },
    { name: "GhostWhite",              values: [248, 248, 255],   category: "white"  },
    { name: "Gold",                    values: [255, 215,   0],   category: "yellow" },
    { name: "GoldenRod",               values: [218, 165,  32],   category: "brown"  },
    { name: "Gray",                    values: [128, 128, 128],   category: "gray"   },
    { name: "Green",                   values: [  0, 128,   0],   category: "green"  },
    { name: "GreenYellow",             values: [173, 255,  47],   category: "green"  },
    { name: "HoneyDew",                values: [240, 255, 240],   category: "white"  },
    { name: "HotPink",                 values: [255, 105, 180],   category: "pink"   },
    { name: "IndianRed",               values: [205,  92,  92],   category: "red"    },
    { name: "Indigo",                  values: [ 75,   0, 130],   category: "purple" },
    { name: "Ivory",                   values: [255, 255, 240],   category: "white"  },
    { name: "Khaki",                   values: [240, 230, 140],   category: "yellow" },
    { name: "Lavender",                values: [230, 230, 250],   category: "purple" },
    { name: "LavenderBlush",           values: [255, 240, 245],   category: "white"  },
    { name: "LawnGreen",               values: [124, 252,   0],   category: "green"  },
    { name: "LemonChiffon",            values: [255, 250, 205],   category: "yellow" },
    { name: "LightBlue",               values: [173, 216, 230],   category: "blue"   },
    { name: "LightCoral",              values: [240, 128, 128],   category: "red"    },
    { name: "LightCyan",               values: [224, 255, 255],   category: "cyan"   },
    { name: "LightGoldenrodYellow",    values: [250, 250, 210],   category: "yellow" },
    { name: "LightGray",               values: [211, 211, 211],   category: "gray"   },
    { name: "LightGreen",              values: [144, 238, 144],   category: "green"  },
    { name: "LightPink",               values: [255, 182, 193],   category: "pink"   },
    { name: "LightSalmon",             values: [255, 160, 122],   category: "red"    },
    { name: "LightSeaGreen",           values: [ 32, 178, 170],   category: "cyan"   },
    { name: "LightSkyBlue",            values: [135, 206, 250],   category: "blue"   },
    { name: "LightSlateGray",          values: [119, 136, 153],   category: "gray"   },
    { name: "LightSteelBlue",          values: [176, 196, 222],   category: "blue"   },
    { name: "LightYellow",             values: [255, 255, 224],   category: "yellow" },
    { name: "Lime",                    values: [  0, 255,   0],   category: "green"  },
    { name: "LimeGreen",               values: [ 50, 205,  50],   category: "green"  },
    { name: "Linen",                   values: [250, 240, 230],   category: "white"  },
    { name: "Magenta",                 values: [255,   0, 255],   category: "purple" },
    { name: "Maroon",                  values: [128,   0,   0],   category: "brown"  },
    { name: "MediumAquaMarine",        values: [102, 205, 170],   category: "cyan"   },
    { name: "MediumBlue",              values: [  0,   0, 205],   category: "blue"   },
    { name: "MediumOrchid",            values: [186,  85, 211],   category: "purple" },
    { name: "MediumPurple",            values: [147, 112, 219],   category: "purple" },
    { name: "MediumSeaGreen",          values: [ 60, 179, 113],   category: "green"  },
    { name: "MediumSlateBlue",         values: [123, 104, 238],   category: "purple" },
    { name: "MediumSpringGreen",       values: [  0, 250, 154],   category: "green"  },
    { name: "MediumTurquoise",         values: [ 72, 209, 204],   category: "cyan"   },
    { name: "MediumVioletRed",         values: [199,  21, 133],   category: "pink"   },
    { name: "MidnightBlue",            values: [ 25,  25, 112],   category: "blue"   },
    { name: "MintCream",               values: [245, 255, 250],   category: "white"  },
    { name: "MistyRose",               values: [255, 228, 225],   category: "white"  },
    { name: "Moccasin",                values: [255, 228, 181],   category: "yellow" },
    { name: "NavajoWhite",             values: [255, 222, 173],   category: "brown"  },
    { name: "Navy",                    values: [  0,   0, 128],   category: "blue"   },
    { name: "OldLace",                 values: [253, 245, 230],   category: "white"  },
    { name: "Olive",                   values: [128, 128,   0],   category: "green"  },
    { name: "OliveDrab",               values: [107, 142,  35],   category: "green"  },
    { name: "Orange",                  values: [255, 165,   0],   category: "orange" },
    { name: "OrangeRed",               values: [255,  69,   0],   category: "orange" },
    { name: "Orchid",                  values: [218, 112, 214],   category: "purple" },
    { name: "PaleGoldenRod",           values: [238, 232, 170],   category: "yellow" },
    { name: "PaleGreen",               values: [152, 251, 152],   category: "green"  },
    { name: "PaleTurquoise",           values: [175, 238, 238],   category: "cyan"   },
    { name: "PaleVioletRed",           values: [219, 112, 147],   category: "pink"   },
    { name: "PapayaWhip",              values: [255, 239, 213],   category: "yellow" },
    { name: "PeachPuff",               values: [255, 218, 185],   category: "yellow" },
    { name: "Peru",                    values: [205, 133,  63],   category: "brown"  },
    { name: "Pink",                    values: [255, 192, 203],   category: "pink"   },
    { name: "Plum",                    values: [221, 160, 221],   category: "purple" },
    { name: "PowderBlue",              values: [176, 224, 230],   category: "blue"   },
    { name: "Purple",                  values: [128,   0, 128],   category: "purple" },
    { name: "RebeccaPurple",           values: [102,  51, 153],   category: "purple" },
    { name: "Red",                     values: [255,   0,   0],   category: "red"    },
    { name: "RosyBrown",               values: [188, 143, 143],   category: "brown"  },
    { name: "RoyalBlue",               values: [ 65, 105, 225],   category: "blue"   },
    { name: "SaddleBrown",             values: [139,  69,  19],   category: "brown"  },
    { name: "Salmon",                  values: [250, 128, 114],   category: "red"    },
    { name: "SandyBrown",              values: [244, 164,  96],   category: "brown"  },
    { name: "SeaGreen",                values: [ 46, 139,  87],   category: "green"  },
    { name: "SeaShell",                values: [255, 245, 238],   category: "white"  },
    { name: "Sienna",                  values: [160,  82,  45],   category: "brown"  },
    { name: "Silver",                  values: [192, 192, 192],   category: "gray"   },
    { name: "SkyBlue",                 values: [135, 206, 235],   category: "blue"   },
    { name: "SlateBlue",               values: [106,  90, 205],   category: "purple" },
    { name: "SlateGray",               values: [112, 128, 144],   category: "gray"   },
    { name: "Snow",                    values: [255, 250, 250],   category: "white"  },
    { name: "SpringGreen",             values: [  0, 255, 127],   category: "green"  },
    { name: "SteelBlue",               values: [ 70, 130, 180],   category: "blue"   },
    { name: "Tan",                     values: [210, 180, 140],   category: "brown"  },
    { name: "Teal",                    values: [  0, 128, 128],   category: "cyan"   },
    { name: "Thistle",                 values: [216, 191, 216],   category: "purple" },
    { name: "Tomato",                  values: [255,  99,  71],   category: "orange" },
    { name: "Turquoise",               values: [ 64, 224, 208],   category: "cyan"   },
    { name: "Violet",                  values: [238, 130, 238],   category: "purple" },
    { name: "Wheat",                   values: [245, 222, 179],   category: "brown"  },
    { name: "White",                   values: [255, 255, 255],   category: "white"  },
    { name: "WhiteSmoke",              values: [245, 245, 245],   category: "white"  },
    { name: "Yellow",                  values: [255, 255,   0],   category: "yellow" },
    { name: "YellowGreen",             values: [154, 205,  50],   category: "green"  },
  ];
  
  var _categories = [
    "All",
    "Red",
    "Green",
    "Blue",
    "Cyan",
    "Orange",
    "Yellow",
    "Brown",
    "Pink",
    "Purple",
    "White",
    "Gray",
  ];
  
  function getCategories() {
    return _categories;
  }
  
  function getColorsByCategory(category) {
    if (category === "all") {
      return _colors;
    }
    
    var colorsByCategory = [];
    
    for (var i = 0, length = _colors.length; i < length; i++) {
      if (_colors[i].category === category) {
        colorsByCategory.push(_colors[i]);
      }
    }
    
    return colorsByCategory;
  }
  
  this.getCategories       = getCategories;
  this.getColorsByCategory = getColorsByCategory;
};